url: https://docacon.com
baseurl: ""
title: Docacon 2020
author: Jonathan Pyle
email: jhpyle@gmail.com
description: "Docacon is the annual conference of the Docassemble user community."
markdown: kramdown
permalink: pretty
exclude:
  - '2019source'
  
